### ISSUE TITLE
Error when compiling Example

### ISSUE THREAD

**Issue by rizgiak** [KIT-MRT/stargazer#2]
Hi, I did your installation tutorial, but i have some problem with executing Example. I installed dependencies correctly, but I think that there is some files that not included in this project.

When i run,
`./devel/lib/stargazer/stargazer_demo res/frame0135.jpg res/stargazer.yaml-cpp`
it says that,
`bash: ./devel/lib/stargazer/stargazer_demo: No such file or directory`

I also check that directory and i couldn't find that executable file. I think some mistakes in CMakeLists.txt that makes this file not compiled.

**Comment by cwecht** [comment]
Thank you for this report. I fixed this issue in #3
